### PR TITLE
Add Horizon Hosting

### PR DESCRIPTION
**Pull request by TechStreetDev**
This pull request adds Horizon Hosting to the hosting providers, we have had a request for this doc in a couple of our support tickets so I decided to make a pull request for it.

### CODE REVIEW

**Comment by henkelmax** [comment]
Please select `dev` as the branch to merge. `master` is the production version of the website.

**Comment by TechStreetDev** [comment]
> Please select `dev` as the branch to merge. `master` is the production version of the website.

That has now been done.

**Comment by henkelmax** [comment]
You didn't properly change the branch. You carried over a lot of commits from master:
image

**Comment by TechStreetDev** [comment]
I see, its making me recreate the pull request so I will do that now

**Pull request closed without merging**
